name: Denver Bike Laws
favicon: null
layout_spectrum: 0.9718044768087566
typography_spectrum: 0.9554430053103715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8264809660613537
  lightness: 0.48154383921064436
  saturation: 0.3535872974898666
  rhythmicContrast: 0.040579128777608275
purpose: []
